project_id = "wndwbcbykcmfzpgbxgho"

[functions.google-calendar]
verify_jwt = true

[functions.spell-check]
verify_jwt = false

[functions.generate-headlines]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false

[functions.revisar-roteiro]
verify_jwt = false

[functions.extract-insumos]
verify_jwt = false

[functions.n8n-insumo]
verify_jwt = false

[functions.n8n-ajustes]
verify_jwt = false
