project_id = "wndwbcbykcmfzpgbxgho"

[functions.google-calendar]
verify_jwt = true

[functions.spell-check]
verify_jwt = false

[functions.generate-headlines]
verify_jwt = false

[functions.n8n-webhook]
verify_jwt = false
